# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 17:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models_logging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changes",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models_logging.Revision",
                verbose_name="to revision",
            ),
        ),
    ]
