# Generated by Django 2.2.24 on 2021-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_logging', '0005_auto_20200804_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='object_id',
            field=models.TextField(help_text='Primary key of the model under version control.'),
        ),
    ]
