# Generated by Django 4.1.11 on 2024-01-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("models_logging", "0008_change_extras"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="change",
            index_together={("content_type", "object_id")},
        ),
    ]
