# Generated by Django 5.2.12 on 2026-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models_logging", "0009_alter_change_index_together"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="change",
            new_name="models_content_type_object_id",
            old_fields=("content_type", "object_id"),
        ),
        migrations.AlterField(
            model_name="change",
            name="action",
            field=models.CharField(
                choices=[
                    ("added", "Added"),
                    ("changed", "Changed"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                help_text="added|changed|deleted",
                max_length=7,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="object_id",
            field=models.TextField(
                db_index=True,
                help_text="Primary key of the model under version control.",
            ),
        ),
        migrations.RemoveField(
            model_name="change",
            name="db",
        ),
    ]
